//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWV_Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_Users
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string Email { get; set; }
        [Required (ErrorMessage = "This fiels is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage = "Passwords doesn't match")]
        public string RePassword { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string AddressLine { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string PostalCode { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string City { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public string Country { get; set; }
        public Nullable<double> Balance { get; set; }
        [Required(ErrorMessage = "This fiels is required")]
        public int AccountTypeID { get; set; }
    
        public virtual T_UserTypes T_UserTypes { get; set; }
    }
}
